spring.application.name=library-crud

# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop

# Initialize DB with data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Enable H2 Console
spring.h2.console.enabled=true
